name: timer
description: A new Flutter project.
publish_to: 'none'

version: 2.0.7+9

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  neumorphic_ui: ^1.0.1
  salomon_bottom_bar: ^3.3.2
  percent_indicator: ^4.2.3
  fl_chart: ^0.66.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/playstorelogo.png"
  min_sdk_android: 21
  ios_assets_catalog: "Timer"

flutter:
  uses-material-design: true
  assets:
    - assets/digi.ttf
    - assets/campfire1.png
    - assets/campfire2.png
    - assets/reach10total.png
    - assets/reach100total.png
    - assets/reach1000total.png
    - assets/reach2avg.png
    - assets/reach4avg.png
    - assets/reach6avg.png
    - assets/reach7TrackedDay.png
    - assets/reach1goal.png
    - assets/reach10goal.png
    - assets/reach100goal.png
  fonts:
    - family: digi
      fonts:
        - asset: assets/digi.ttf
